DROP TABLE IF EXISTS SUBSIDIARIES;
DROP TABLE IF EXISTS CONSEJERAS;
DROP TABLE IF EXISTS TIENDAS;
DROP TABLE IF EXISTS MARCAS;
DROP TABLE IF EXISTS USERS;


CREATE TABLE SUBSIDIARIES (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    entityname TEXT UNIQUE NOT NULL,
    mailchimpentityid TEXT UNIQUE NOT NULL
);

CREATE TABLE CONSEJERAS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    fullname TEXT NOT NULL,
    subsidiary_id INTEGER NOT NULL,
    FOREIGN KEY (subsidiary_id) REFERENCES SUBSIDIARIES (id)
);

CREATE TABLE TIENDAS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    storename TEXT UNIQUE NOT NULL,
    subsidiary_id INTEGER NOT NULL,
    FOREIGN KEY (subsidiary_id) REFERENCES SUBSIDIARIES (id)
);

CREATE TABLE MARCAS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    brandname TEXT NOT NULL,
    brandid TEXT UNIQUE NOT NULL,
    subsidiary_id INTEGER NOT NULL,
    FOREIGN KEY (subsidiary_id) REFERENCES SUBSIDIARIES (id)
);

CREATE TABLE USERS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);
