CREATE TABLE IF NOT EXISTS SUBSIDIARIES (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    entityname TEXT UNIQUE NOT NULL,
    mailchimpentityid TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS CONSEJERAS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    fullname TEXT NOT NULL,
    subsidiaryid INTEGER NOT NULL,
    FOREIGN KEY (subsidiaryid) REFERENCES SUBSIDIARIES (id)
);

CREATE TABLE IF NOT EXISTS TIENDAS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    storename TEXT UNIQUE NOT NULL,
    subsidiaryid INTEGER NOT NULL,
    FOREIGN KEY (subsidiaryid) REFERENCES SUBSIDIARIES (id)
);

CREATE TABLE IF NOT EXISTS MARCAS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    brandname TEXT NOT NULL,
    brandcode TEXT UNIQUE NOT NULL,
    subsidiaryid INTEGER NOT NULL,
    FOREIGN KEY (subsidiaryid) REFERENCES SUBSIDIARIES (id)
);

CREATE TABLE IF NOT EXISTS USERS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    subsidiary_id INTEGER,
    role TEXT NOT NULL DEFAULT 'user',
    FOREIGN KEY (subsidiary_id) REFERENCES SUBSIDIARIES (id)
);

CREATE TABLE IF NOT EXISTS POS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    pos_name TEXT UNIQUE NOT NULL,
    subsidiaryid INTEGER NOT NULL,
    FOREIGN KEY (subsidiaryid) REFERENCES SUBSIDIARIES (id)
);

CREATE TABLE IF NOT EXISTS TESTERS (
    testercode TEXT PRIMARY KEY UNIQUE NOT NULL,
    barcode TEXT NULL,
    tester_name TEXT NOT NULL,
    tester_id INTEGER NOT NULL,
    tester_axe TEXT CHECK(LENGTH(tester_axe) <= 4),
    subsidiaryid INTEGER NOT NULL,
    FOREIGN KEY (subsidiaryid) REFERENCES SUBSIDIARIES (id),
    FOREIGN KEY (tester_id) REFERENCES MARCAS (id)
);

CREATE TABLE IF NOT EXISTS ORDEREDTESTERS (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  itemcode TEXT NOT NULL,
  orderdate TEXT NOT NULL,
  requester TEXT NOT NULL,
  orderpos INTEGER NOT NULL,
  subsidiary INTEGER NOT NULL,
  FOREIGN KEY (orderpos) REFERENCES POS (id),
  FOREIGN KEY (subsidiary) REFERENCES SUBSIDIARIES (id)
);
