DROP TABLE IF EXISTS SUBSIDIARIES;
DROP TABLE IF EXISTS CONSEJERAS;
DROP TABLE IF EXISTS TIENDAS;
DROP TABLE IF EXISTS TESTERS;
DROP TABLE IF EXISTS MARCAS;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS POS;


CREATE TABLE SUBSIDIARIES (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    entityname TEXT UNIQUE NOT NULL,
    mailchimpentityid TEXT UNIQUE NOT NULL
);

CREATE TABLE CONSEJERAS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    fullname TEXT NOT NULL,
    subsidiaryid INTEGER NOT NULL,
    FOREIGN KEY (subsidiaryid) REFERENCES SUBSIDIARIES (id)
);

CREATE TABLE TIENDAS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    storename TEXT UNIQUE NOT NULL,
    subsidiaryid INTEGER NOT NULL,
    FOREIGN KEY (subsidiaryid) REFERENCES SUBSIDIARIES (id)
);

CREATE TABLE MARCAS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    brandname TEXT NOT NULL,
    brandcode TEXT UNIQUE NOT NULL,
    subsidiaryid INTEGER NOT NULL,
    FOREIGN KEY (subsidiaryid) REFERENCES SUBSIDIARIES (id)
);

CREATE TABLE USERS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    subsidiary_id INTEGER,
    FOREIGN KEY (subsidiary_id) REFERENCES SUBSIDIARIES (id)
);

CREATE TABLE POS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    pos_name TEXT UNIQUE NOT NULL,
    subsidiaryid INTEGER NOT NULL,
    FOREIGN KEY (subsidiaryid) REFERENCES SUBSIDIARIES (id)
);

CREATE TABLE TESTERS (
    testercode TEXT PRIMARY KEY UNIQUE NOT NULL,
    barcode TEXT NULL,
    tester_name TEXT NOT NULL,
    tester_id INTEGER NOT NULL,
    tester_axe TEXT CHECK(LENGTH(tester_axe) <= 4),
    subsidiaryid INTEGER NOT NULL,
    FOREIGN KEY (subsidiaryid) REFERENCES SUBSIDIARIES (id),
    FOREIGN KEY (tester_id) REFERENCES MARCAS (id)
);

CREATE TABLE ORDEREDTESTERS (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  itemcode TEXT NOT NULL,
  orderdate TEXT NOT NULL,
  requester TEXT NOT NULL,
  orderpos INTEGER NOT NULL,
  subsidiary INTEGER NOT NULL,
  FOREIGN KEY (orderpos) REFERENCES POS (id),
  FOREIGN KEY (subsidiary) REFERENCES SUBSIDIARIES (id)
);
